# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfour', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='portfolio',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='department',
            field=models.CharField(choices=[('TRAVELMATE_SOLUTION', 'TRAVELMATE_SOLUTION'), ('TRAVIDUX_TECHNOLOGIES', 'TRAVIDUX_TECHNOLOGIES')], default='TRAVELMATE_SOLUTION', max_length=21),
        ),
    ]
