# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfour', '0002_auto_20171028_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='department',
            field=models.CharField(choices=[('Travelmate Solutons', 'Travelmate Solutons'), ('Travidux Technologies', 'Travidux Technologies')], default='Travelmate Solutons', max_length=21),
        ),
    ]
