# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 06:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appfour', '0003_auto_20171028_0456'),
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TravelDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('desitination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places2', to='appfour.Places')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places1', to='appfour.Places')),
            ],
        ),
    ]
