# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appfour', '0005_auto_20171028_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='confirm_password',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='traveldetails',
            name='desitination',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='places2', to='appfour.Places'),
        ),
        migrations.AlterField(
            model_name='traveldetails',
            name='origin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='places1', to='appfour.Places'),
        ),
    ]
