# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfour', '0008_auto_20171028_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='places',
            name='amount',
        ),
        migrations.AddField(
            model_name='traveldetails',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
    ]
