# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20171109_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeentrydata',
            name='emp_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='employeeentrydata',
            name='emp_report',
            field=models.CharField(max_length=200),
        ),
    ]
