# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 11:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20171109_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavemodel',
            name='emp_LeaveUserName',
        ),
    ]
