# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 11:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeEntryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_email', models.EmailField(max_length=200, unique=True)),
                ('emp_code', models.CharField(max_length=3, unique=True)),
                ('emp_datejoin', models.DateField()),
                ('emp_report', models.CharField(max_length=200, unique=True)),
                ('emp_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_leavedate', models.DateField(unique=True)),
                ('emp_leavesanction', models.BooleanField()),
                ('emp_LeaveUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
