# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activatemodel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='leavemodel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
