# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeEntryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=200)),
                ('emp_code', models.CharField(max_length=3, unique=True)),
                ('emp_email', models.EmailField(max_length=254, unique=True)),
                ('emp_password1', models.CharField(max_length=32)),
                ('emp_password2', models.CharField(max_length=32)),
                ('emp_datejoin', models.DateField()),
                ('emp_role', models.CharField(choices=[('Developer', 'Developer'), ('Project Head', 'Project Head'), ('Team lead', 'Team lead')], default='Developer', max_length=200)),
                ('emp_report', models.DateField()),
            ],
        ),
    ]
