# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appfour', '0009_auto_20171028_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveldetails',
            name='details',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='traveldetails',
            name='amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='traveldetails',
            name='desitination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places2', to='appfour.Places'),
        ),
        migrations.AlterField(
            model_name='traveldetails',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places1', to='appfour.Places'),
        ),
    ]
