# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 04:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appfour', '0012_auto_20171030_0416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traveldetails',
            old_name='username',
            new_name='author',
        ),
    ]
