# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 04:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appfour', '0013_auto_20171030_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveldetails',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
