# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfour', '0017_auto_20171030_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveldetails',
            name='desitination',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='traveldetails',
            name='origin',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Places',
        ),
    ]
