# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 09:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfour', '0018_auto_20171030_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveldetails',
            name='created_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
